# PHP CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-php/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: circleci/php:7.0-browsers
    working_directory: ~/laravel
    steps:
      - checkout

      #https://askubuntu.com/questions/594656/how-to-install-the-latest-versions-of-nodejs-and-npm
      #We are using Node JS 6 because that's the current version on our local vagrant/homestead machines
      - run:
         name: Download NodeJS v6
         command: curl -sL https://deb.nodesource.com/setup_6.x | sudo -E bash -
